### ISSUE TITLE
hello! Can we have this with react version 18.2.0

### ISSUE THREAD

**Issue by delucasange** [filipecorrea/react-image-hotspots#60]
Hi!
Great component btw!
I was able to style it perfectly!

The issue at the moment is that i cannot deploy as it has react v16ish as a peer dependency while im using this with above react 18.

Can you update please?
Thanks!

**Comment by filipecorrea** [comment]
@delucasange can you help me to check https://www.npmjs.com/package/react-image-hotspots/v/2.0.0?

**Comment by delucasange** [comment]
@filipecorrea works perfectly!!! 👯 Tysm!!
